
/**
 * This class encapsulates a data value generated by a sensor and other metadata
 */
public class DataPacket {

    //Time at which the data value was created/read
    private String time_of_creation;

    //Object that produced the data value (most likely a sensor)
    private String sourceObjectName;

    //Field in the sensor whose value is encapsulated in the DataPacket. For example, "Motor Speed" 
    private String fieldName ;

    //Value of a specific field in the sensor. For example, "59 RPM"
    private String value;

    //Size in bytes of the returned value
    private int size;
    
    /**
     * Constructor
     * @param sourceObjectName
     * @param fieldName
     * @param value
     * @param size
     * @param time_of_creation
     */
    public DataPacket(String sourceObjectName, String fieldName, String value, int size, String time_of_creation) {
        this.sourceObjectName = sourceObjectName;
        this.fieldName = fieldName;
        this.value = value;
        this.size = size;
        this.time_of_creation = time_of_creation;
    }

    /**
     * Getter
     * @return sourceObjectName
     */
    public String getSourceObjectName() {
        return sourceObjectName;
    }

    /**
     * Getter
     * @return fieldName
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Getter
     * @return value
     */
    public String getValue() {
        return value;
    }

    /**
     * Getter
     * @return size
     */
    public int getSize() {
        return size;
    }

    /**
     * Getter
     * @return time_of_creation
     */
    public String getTime_of_creation() {
        return time_of_creation;
    }

    /**
     * Function to generate a header for a CSV file to store DataPacket objects.
     * This header represents the member variables of the DataPacket class
     * @return header
     */
    public static String getHeader(){
        return "Time of Creation, Source Object, Field Name, Value, Size";
    }

    /**
     * Function to generate a data row representing a DataPacket object to be
     * added to a CSV file.
     * @return string representation of the packet's values joined by commas
     */
    @Override
    public String toString() {
        return String.format("%s,%s,%s,%s,%d",
        time_of_creation, sourceObjectName, fieldName, value, size);
    }
    

    
}
